### ISSUE TITLE
it goes silent

### ISSUE THREAD

**Issue by higaru2** [xxiangcoding/nameless-nightmare#1]
hello:)
fabulous sound out of this script:) bigups!
problem is that after a while it goes silent...
any chance for a fix?

also
I would really love to see this script with less pretty grafx but more controlls over the grains and sound:)
maybe v2... :)
big thanks!

**Comment by xO-xN** [comment]
Hello Higaru, thank you for your feedback.

The silence might be due to the overloading of the Norns' CPU, as some of the engines (planets) use a large amount of CPU. Using multiple engines at the same time might cause the Norns' sound engine to break down and go silent. This can also happen if you turn an engine on and off too quickly or switch engines too fast. If this is the case, you can try slowing down the on/off triggering to let Norns free up some CPU space for the new engine.

I might tweak some engines in a future update to make them sound better, and adding more control options for the grains and sound is a good idea! Thank you.

**Comment by higaru2** [comment]
thank you mister X:)
I'll try your advices
and looking fwd for the tweakable version
with more controll
because your engines sound quite unique!

**Comment by higaru2** [comment]
I would love to be able to play it live
without fear of silence:)

this is the things that I do:
https://newromanianweird.bandcamp.com/album/live-at-x-imental-5

**Comment by xO-xN** [comment]
You can try out the new v0.8.1 update (available for download in Releases). It may solve your problem.

This version still has some bugs to fix, but I think it should be more stable compared to the last version.

**Comment by higaru2** [comment]
thank you!
